apiVersion: apps/v1
kind: Deployment
metadata:
  name: odh-dashboard
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: odh-dashboard
          image: quay.io/opendatahub/odh-dashboard:latest
