apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DASHBOARD_APP}
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: rhods-dashboard
          image: ${IMAGE_REPOSITORY}
